# coding: utf-8

"""
    CMS Contribution API

    The CMS Contribution API allows access and modification of Lumapps contents.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class AttachedLink(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "title": "str",
        "description": "str",
        "url": "str",
        "image": "BlockImage",
        "video_id": "str",
    }

    attribute_map = {
        "title": "title",
        "description": "description",
        "url": "url",
        "image": "image",
        "video_id": "videoId",
    }

    def __init__(
        self, title=None, description=None, url=None, image=None, video_id=None
    ):  # noqa: E501
        """AttachedLink - a model defined in Swagger"""  # noqa: E501
        self._title = None
        self._description = None
        self._url = None
        self._image = None
        self._video_id = None
        self.discriminator = None
        if title is not None:
            self.title = title
        if description is not None:
            self.description = description
        self.url = url
        if image is not None:
            self.image = image
        if video_id is not None:
            self.video_id = video_id

    @property
    def title(self):
        """Gets the title of this AttachedLink.  # noqa: E501

        The link's title.  # noqa: E501

        :return: The title of this AttachedLink.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this AttachedLink.

        The link's title.  # noqa: E501

        :param title: The title of this AttachedLink.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def description(self):
        """Gets the description of this AttachedLink.  # noqa: E501

        The link's description.  # noqa: E501

        :return: The description of this AttachedLink.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this AttachedLink.

        The link's description.  # noqa: E501

        :param description: The description of this AttachedLink.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def url(self):
        """Gets the url of this AttachedLink.  # noqa: E501

        The link's url.  # noqa: E501

        :return: The url of this AttachedLink.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this AttachedLink.

        The link's url.  # noqa: E501

        :param url: The url of this AttachedLink.  # noqa: E501
        :type: str
        """
        if url is None:
            raise ValueError(
                "Invalid value for `url`, must not be `None`"
            )  # noqa: E501

        self._url = url

    @property
    def image(self):
        """Gets the image of this AttachedLink.  # noqa: E501


        :return: The image of this AttachedLink.  # noqa: E501
        :rtype: BlockImage
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this AttachedLink.


        :param image: The image of this AttachedLink.  # noqa: E501
        :type: BlockImage
        """

        self._image = image

    @property
    def video_id(self):
        """Gets the video_id of this AttachedLink.  # noqa: E501

        The id of the video, if applicable.  # noqa: E501

        :return: The video_id of this AttachedLink.  # noqa: E501
        :rtype: str
        """
        return self._video_id

    @video_id.setter
    def video_id(self, video_id):
        """Sets the video_id of this AttachedLink.

        The id of the video, if applicable.  # noqa: E501

        :param video_id: The video_id of this AttachedLink.  # noqa: E501
        :type: str
        """

        self._video_id = video_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(AttachedLink, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AttachedLink):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
