# coding: utf-8

"""
    CMS Contribution API

    The CMS Contribution API allows access and modification of Lumapps contents.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from .base_block import BaseBlock  # noqa: F401,E501


class BlockHtml(BaseBlock):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"html": "str", "popin": "str"}
    if hasattr(BaseBlock, "swagger_types"):
        swagger_types.update(BaseBlock.swagger_types)

    attribute_map = {"html": "html", "popin": "popin"}
    if hasattr(BaseBlock, "attribute_map"):
        attribute_map.update(BaseBlock.attribute_map)

    def __init__(self, html=None, popin=None, *args, **kwargs):  # noqa: E501
        """BlockHtml - a model defined in Swagger"""  # noqa: E501
        self._html = None
        self._popin = None
        self.discriminator = None
        self.html = html
        if popin is not None:
            self.popin = popin
        BaseBlock.__init__(self, *args, **kwargs)

    @property
    def html(self):
        """Gets the html of this BlockHtml.  # noqa: E501

        The html content.  # noqa: E501

        :return: The html of this BlockHtml.  # noqa: E501
        :rtype: str
        """
        return self._html

    @html.setter
    def html(self, html):
        """Sets the html of this BlockHtml.

        The html content.  # noqa: E501

        :param html: The html of this BlockHtml.  # noqa: E501
        :type: str
        """
        if html is None:
            raise ValueError(
                "Invalid value for `html`, must not be `None`"
            )  # noqa: E501

        self._html = html

    @property
    def popin(self):
        """Gets the popin of this BlockHtml.  # noqa: E501

        The popin content.  # noqa: E501

        :return: The popin of this BlockHtml.  # noqa: E501
        :rtype: str
        """
        return self._popin

    @popin.setter
    def popin(self, popin):
        """Sets the popin of this BlockHtml.

        The popin content.  # noqa: E501

        :param popin: The popin of this BlockHtml.  # noqa: E501
        :type: str
        """

        self._popin = popin

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(BlockHtml, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BlockHtml):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
