# coding: utf-8

"""
    CMS Contribution API

    The CMS Contribution API allows access and modification of Lumapps contents.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from .base_block import BaseBlock  # noqa: F401,E501


class BlockTagFilter(BaseBlock):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"tags": "list[TagReference]", "is_no_filter_allowed": "bool"}
    if hasattr(BaseBlock, "swagger_types"):
        swagger_types.update(BaseBlock.swagger_types)

    attribute_map = {"tags": "tags", "is_no_filter_allowed": "isNoFilterAllowed"}
    if hasattr(BaseBlock, "attribute_map"):
        attribute_map.update(BaseBlock.attribute_map)

    def __init__(
        self, tags=None, is_no_filter_allowed=True, *args, **kwargs
    ):  # noqa: E501
        """BlockTagFilter - a model defined in Swagger"""  # noqa: E501
        self._tags = None
        self._is_no_filter_allowed = None
        self.discriminator = None
        self.tags = tags
        self.is_no_filter_allowed = is_no_filter_allowed
        BaseBlock.__init__(self, *args, **kwargs)

    @property
    def tags(self):
        """Gets the tags of this BlockTagFilter.  # noqa: E501


        :return: The tags of this BlockTagFilter.  # noqa: E501
        :rtype: list[TagReference]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this BlockTagFilter.


        :param tags: The tags of this BlockTagFilter.  # noqa: E501
        :type: list[TagReference]
        """
        if tags is None:
            raise ValueError(
                "Invalid value for `tags`, must not be `None`"
            )  # noqa: E501

        self._tags = tags

    @property
    def is_no_filter_allowed(self):
        """Gets the is_no_filter_allowed of this BlockTagFilter.  # noqa: E501


        :return: The is_no_filter_allowed of this BlockTagFilter.  # noqa: E501
        :rtype: bool
        """
        return self._is_no_filter_allowed

    @is_no_filter_allowed.setter
    def is_no_filter_allowed(self, is_no_filter_allowed):
        """Sets the is_no_filter_allowed of this BlockTagFilter.


        :param is_no_filter_allowed: The is_no_filter_allowed of this BlockTagFilter.  # noqa: E501
        :type: bool
        """
        if is_no_filter_allowed is None:
            raise ValueError(
                "Invalid value for `is_no_filter_allowed`, must not be `None`"
            )  # noqa: E501

        self._is_no_filter_allowed = is_no_filter_allowed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(BlockTagFilter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BlockTagFilter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
