# coding: utf-8

"""
    CMS Contribution API

    The CMS Contribution API allows access and modification of Lumapps contents.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from .base_block import BaseBlock  # noqa: F401,E501


class BlockStructuredContent(BaseBlock):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"structured_content_id": "str", "dita": "object"}
    if hasattr(BaseBlock, "swagger_types"):
        swagger_types.update(BaseBlock.swagger_types)

    attribute_map = {"structured_content_id": "structuredContentId", "dita": "dita"}
    if hasattr(BaseBlock, "attribute_map"):
        attribute_map.update(BaseBlock.attribute_map)

    def __init__(
        self, structured_content_id=None, dita=None, *args, **kwargs
    ):  # noqa: E501
        """BlockStructuredContent - a model defined in Swagger"""  # noqa: E501
        self._structured_content_id = None
        self._dita = None
        self.discriminator = None
        self.structured_content_id = structured_content_id
        self.dita = dita
        BaseBlock.__init__(self, *args, **kwargs)

    @property
    def structured_content_id(self):
        """Gets the structured_content_id of this BlockStructuredContent.  # noqa: E501

        The id of the associated structured content entity  # noqa: E501

        :return: The structured_content_id of this BlockStructuredContent.  # noqa: E501
        :rtype: str
        """
        return self._structured_content_id

    @structured_content_id.setter
    def structured_content_id(self, structured_content_id):
        """Sets the structured_content_id of this BlockStructuredContent.

        The id of the associated structured content entity  # noqa: E501

        :param structured_content_id: The structured_content_id of this BlockStructuredContent.  # noqa: E501
        :type: str
        """
        if structured_content_id is None:
            raise ValueError(
                "Invalid value for `structured_content_id`, must not be `None`"
            )  # noqa: E501

        self._structured_content_id = structured_content_id

    @property
    def dita(self):
        """Gets the dita of this BlockStructuredContent.  # noqa: E501

        The dita document to display  # noqa: E501

        :return: The dita of this BlockStructuredContent.  # noqa: E501
        :rtype: object
        """
        return self._dita

    @dita.setter
    def dita(self, dita):
        """Sets the dita of this BlockStructuredContent.

        The dita document to display  # noqa: E501

        :param dita: The dita of this BlockStructuredContent.  # noqa: E501
        :type: object
        """
        if dita is None:
            raise ValueError(
                "Invalid value for `dita`, must not be `None`"
            )  # noqa: E501

        self._dita = dita

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(BlockStructuredContent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BlockStructuredContent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
