# coding: utf-8

"""
    CMS Contribution API

    The CMS Contribution API allows access and modification of Lumapps contents.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from .base_block import BaseBlock  # noqa: F401,E501


class BlockResourceCreationInfo(BaseBlock):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "resource_type": "str",
        "resource_id": "str",
        "author": "BlockUser",
        "created_at": "datetime",
    }
    if hasattr(BaseBlock, "swagger_types"):
        swagger_types.update(BaseBlock.swagger_types)

    attribute_map = {
        "resource_type": "resourceType",
        "resource_id": "resourceId",
        "author": "author",
        "created_at": "createdAt",
    }
    if hasattr(BaseBlock, "attribute_map"):
        attribute_map.update(BaseBlock.attribute_map)

    def __init__(
        self,
        resource_type=None,
        resource_id=None,
        author=None,
        created_at=None,
        *args,
        **kwargs
    ):  # noqa: E501
        """BlockResourceCreationInfo - a model defined in Swagger"""  # noqa: E501
        self._resource_type = None
        self._resource_id = None
        self._author = None
        self._created_at = None
        self.discriminator = None
        self.resource_type = resource_type
        self.resource_id = resource_id
        self.author = author
        self.created_at = created_at
        BaseBlock.__init__(self, *args, **kwargs)

    @property
    def resource_type(self):
        """Gets the resource_type of this BlockResourceCreationInfo.  # noqa: E501

        The type of the associated resource.  # noqa: E501

        :return: The resource_type of this BlockResourceCreationInfo.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this BlockResourceCreationInfo.

        The type of the associated resource.  # noqa: E501

        :param resource_type: The resource_type of this BlockResourceCreationInfo.  # noqa: E501
        :type: str
        """
        if resource_type is None:
            raise ValueError(
                "Invalid value for `resource_type`, must not be `None`"
            )  # noqa: E501

        self._resource_type = resource_type

    @property
    def resource_id(self):
        """Gets the resource_id of this BlockResourceCreationInfo.  # noqa: E501

        The id of the associated resource.  # noqa: E501

        :return: The resource_id of this BlockResourceCreationInfo.  # noqa: E501
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id):
        """Sets the resource_id of this BlockResourceCreationInfo.

        The id of the associated resource.  # noqa: E501

        :param resource_id: The resource_id of this BlockResourceCreationInfo.  # noqa: E501
        :type: str
        """
        if resource_id is None:
            raise ValueError(
                "Invalid value for `resource_id`, must not be `None`"
            )  # noqa: E501

        self._resource_id = resource_id

    @property
    def author(self):
        """Gets the author of this BlockResourceCreationInfo.  # noqa: E501


        :return: The author of this BlockResourceCreationInfo.  # noqa: E501
        :rtype: BlockUser
        """
        return self._author

    @author.setter
    def author(self, author):
        """Sets the author of this BlockResourceCreationInfo.


        :param author: The author of this BlockResourceCreationInfo.  # noqa: E501
        :type: BlockUser
        """
        if author is None:
            raise ValueError(
                "Invalid value for `author`, must not be `None`"
            )  # noqa: E501

        self._author = author

    @property
    def created_at(self):
        """Gets the created_at of this BlockResourceCreationInfo.  # noqa: E501

        The date and time when the resource was created  # noqa: E501

        :return: The created_at of this BlockResourceCreationInfo.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this BlockResourceCreationInfo.

        The date and time when the resource was created  # noqa: E501

        :param created_at: The created_at of this BlockResourceCreationInfo.  # noqa: E501
        :type: datetime
        """
        if created_at is None:
            raise ValueError(
                "Invalid value for `created_at`, must not be `None`"
            )  # noqa: E501

        self._created_at = created_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(BlockResourceCreationInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BlockResourceCreationInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
