# coding: utf-8

"""
    CMS Contribution API

    The CMS Contribution API allows access and modification of Lumapps contents.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from .base_block import BaseBlock  # noqa: F401,E501


class BlockList(BaseBlock):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "orientation": "ContainerOrientation",
        "variant": "ContainerVariant",
        "items": "list[object]",
    }
    if hasattr(BaseBlock, "swagger_types"):
        swagger_types.update(BaseBlock.swagger_types)

    attribute_map = {
        "orientation": "orientation",
        "variant": "variant",
        "items": "items",
    }
    if hasattr(BaseBlock, "attribute_map"):
        attribute_map.update(BaseBlock.attribute_map)

    def __init__(
        self, orientation=None, variant=None, items=None, *args, **kwargs
    ):  # noqa: E501
        """BlockList - a model defined in Swagger"""  # noqa: E501
        self._orientation = None
        self._variant = None
        self._items = None
        self.discriminator = None
        self.orientation = orientation
        self.variant = variant
        self.items = items
        BaseBlock.__init__(self, *args, **kwargs)

    @property
    def orientation(self):
        """Gets the orientation of this BlockList.  # noqa: E501


        :return: The orientation of this BlockList.  # noqa: E501
        :rtype: ContainerOrientation
        """
        return self._orientation

    @orientation.setter
    def orientation(self, orientation):
        """Sets the orientation of this BlockList.


        :param orientation: The orientation of this BlockList.  # noqa: E501
        :type: ContainerOrientation
        """
        if orientation is None:
            raise ValueError(
                "Invalid value for `orientation`, must not be `None`"
            )  # noqa: E501

        self._orientation = orientation

    @property
    def variant(self):
        """Gets the variant of this BlockList.  # noqa: E501


        :return: The variant of this BlockList.  # noqa: E501
        :rtype: ContainerVariant
        """
        return self._variant

    @variant.setter
    def variant(self, variant):
        """Sets the variant of this BlockList.


        :param variant: The variant of this BlockList.  # noqa: E501
        :type: ContainerVariant
        """
        if variant is None:
            raise ValueError(
                "Invalid value for `variant`, must not be `None`"
            )  # noqa: E501

        self._variant = variant

    @property
    def items(self):
        """Gets the items of this BlockList.  # noqa: E501

        The list's items.  # noqa: E501

        :return: The items of this BlockList.  # noqa: E501
        :rtype: list[object]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this BlockList.

        The list's items.  # noqa: E501

        :param items: The items of this BlockList.  # noqa: E501
        :type: list[object]
        """
        if items is None:
            raise ValueError(
                "Invalid value for `items`, must not be `None`"
            )  # noqa: E501

        self._items = items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(BlockList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BlockList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
