# coding: utf-8

"""
    CMS Contribution API

    The CMS Contribution API allows access and modification of Lumapps contents.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from .base_block import BaseBlock  # noqa: F401,E501


class BlockTabFilteredContainer(BaseBlock):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"filter": "object", "container": "object"}
    if hasattr(BaseBlock, "swagger_types"):
        swagger_types.update(BaseBlock.swagger_types)

    attribute_map = {"filter": "filter", "container": "container"}
    if hasattr(BaseBlock, "attribute_map"):
        attribute_map.update(BaseBlock.attribute_map)

    def __init__(self, filter=None, container=None, *args, **kwargs):  # noqa: E501
        """BlockTabFilteredContainer - a model defined in Swagger"""  # noqa: E501
        self._filter = None
        self._container = None
        self.discriminator = None
        self.filter = filter
        self.container = container
        BaseBlock.__init__(self, *args, **kwargs)

    @property
    def filter(self):
        """Gets the filter of this BlockTabFilteredContainer.  # noqa: E501


        :return: The filter of this BlockTabFilteredContainer.  # noqa: E501
        :rtype: object
        """
        return self._filter

    @filter.setter
    def filter(self, filter):
        """Sets the filter of this BlockTabFilteredContainer.


        :param filter: The filter of this BlockTabFilteredContainer.  # noqa: E501
        :type: object
        """
        if filter is None:
            raise ValueError(
                "Invalid value for `filter`, must not be `None`"
            )  # noqa: E501

        self._filter = filter

    @property
    def container(self):
        """Gets the container of this BlockTabFilteredContainer.  # noqa: E501


        :return: The container of this BlockTabFilteredContainer.  # noqa: E501
        :rtype: object
        """
        return self._container

    @container.setter
    def container(self, container):
        """Sets the container of this BlockTabFilteredContainer.


        :param container: The container of this BlockTabFilteredContainer.  # noqa: E501
        :type: object
        """
        if container is None:
            raise ValueError(
                "Invalid value for `container`, must not be `None`"
            )  # noqa: E501

        self._container = container

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(BlockTabFilteredContainer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BlockTabFilteredContainer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
