# coding: utf-8

"""
    CMS Contribution API

    The CMS Contribution API allows access and modification of Lumapps contents.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class CreateArticleInContainerRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "dita": "MultilangObject",
        "template_id": "str",
        "container": "ContainerReference",
    }

    attribute_map = {
        "dita": "dita",
        "template_id": "templateId",
        "container": "container",
    }

    def __init__(self, dita=None, template_id=None, container=None):  # noqa: E501
        """CreateArticleInContainerRequest - a model defined in Swagger"""  # noqa: E501
        self._dita = None
        self._template_id = None
        self._container = None
        self.discriminator = None
        self.dita = dita
        self.template_id = template_id
        self.container = container

    @property
    def dita(self):
        """Gets the dita of this CreateArticleInContainerRequest.  # noqa: E501


        :return: The dita of this CreateArticleInContainerRequest.  # noqa: E501
        :rtype: MultilangObject
        """
        return self._dita

    @dita.setter
    def dita(self, dita):
        """Sets the dita of this CreateArticleInContainerRequest.


        :param dita: The dita of this CreateArticleInContainerRequest.  # noqa: E501
        :type: MultilangObject
        """
        if dita is None:
            raise ValueError(
                "Invalid value for `dita`, must not be `None`"
            )  # noqa: E501

        self._dita = dita

    @property
    def template_id(self):
        """Gets the template_id of this CreateArticleInContainerRequest.  # noqa: E501

        The id of the template used to display the article  # noqa: E501

        :return: The template_id of this CreateArticleInContainerRequest.  # noqa: E501
        :rtype: str
        """
        return self._template_id

    @template_id.setter
    def template_id(self, template_id):
        """Sets the template_id of this CreateArticleInContainerRequest.

        The id of the template used to display the article  # noqa: E501

        :param template_id: The template_id of this CreateArticleInContainerRequest.  # noqa: E501
        :type: str
        """
        if template_id is None:
            raise ValueError(
                "Invalid value for `template_id`, must not be `None`"
            )  # noqa: E501

        self._template_id = template_id

    @property
    def container(self):
        """Gets the container of this CreateArticleInContainerRequest.  # noqa: E501


        :return: The container of this CreateArticleInContainerRequest.  # noqa: E501
        :rtype: ContainerReference
        """
        return self._container

    @container.setter
    def container(self, container):
        """Sets the container of this CreateArticleInContainerRequest.


        :param container: The container of this CreateArticleInContainerRequest.  # noqa: E501
        :type: ContainerReference
        """
        if container is None:
            raise ValueError(
                "Invalid value for `container`, must not be `None`"
            )  # noqa: E501

        self._container = container

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(CreateArticleInContainerRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateArticleInContainerRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
