# coding: utf-8

"""
    CMS Contribution API

    The CMS Contribution API allows access and modification of Lumapps contents.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from .link_label import LinkLabel  # noqa: F401,E501


class CustomLinkLabel(LinkLabel):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"value": "I18nString", "icon": "str"}
    if hasattr(LinkLabel, "swagger_types"):
        swagger_types.update(LinkLabel.swagger_types)

    attribute_map = {"value": "value", "icon": "icon"}
    if hasattr(LinkLabel, "attribute_map"):
        attribute_map.update(LinkLabel.attribute_map)

    def __init__(self, value=None, icon=None, *args, **kwargs):  # noqa: E501
        """CustomLinkLabel - a model defined in Swagger"""  # noqa: E501
        self._value = None
        self._icon = None
        self.discriminator = None
        if value is not None:
            self.value = value
        if icon is not None:
            self.icon = icon
        LinkLabel.__init__(self, *args, **kwargs)

    @property
    def value(self):
        """Gets the value of this CustomLinkLabel.  # noqa: E501


        :return: The value of this CustomLinkLabel.  # noqa: E501
        :rtype: I18nString
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this CustomLinkLabel.


        :param value: The value of this CustomLinkLabel.  # noqa: E501
        :type: I18nString
        """

        self._value = value

    @property
    def icon(self):
        """Gets the icon of this CustomLinkLabel.  # noqa: E501

        The icon of the link label.  # noqa: E501

        :return: The icon of this CustomLinkLabel.  # noqa: E501
        :rtype: str
        """
        return self._icon

    @icon.setter
    def icon(self, icon):
        """Sets the icon of this CustomLinkLabel.

        The icon of the link label.  # noqa: E501

        :param icon: The icon of this CustomLinkLabel.  # noqa: E501
        :type: str
        """

        self._icon = icon

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(CustomLinkLabel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomLinkLabel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
