# coding: utf-8

"""
    CMS Contribution API

    The CMS Contribution API allows access and modification of Lumapps contents.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Footer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "label": "str",
        "icon": "str",
        "style": "ElementStyle",
        "url": "str",
        "resource_type": "str",
        "resource_id": "str",
    }

    attribute_map = {
        "label": "label",
        "icon": "icon",
        "style": "style",
        "url": "url",
        "resource_type": "resourceType",
        "resource_id": "resourceId",
    }

    def __init__(
        self,
        label=None,
        icon=None,
        style=None,
        url=None,
        resource_type=None,
        resource_id=None,
    ):  # noqa: E501
        """Footer - a model defined in Swagger"""  # noqa: E501
        self._label = None
        self._icon = None
        self._style = None
        self._url = None
        self._resource_type = None
        self._resource_id = None
        self.discriminator = None
        if label is not None:
            self.label = label
        if icon is not None:
            self.icon = icon
        if style is not None:
            self.style = style
        if url is not None:
            self.url = url
        if resource_type is not None:
            self.resource_type = resource_type
        if resource_id is not None:
            self.resource_id = resource_id

    @property
    def label(self):
        """Gets the label of this Footer.  # noqa: E501

        The footer's text.  # noqa: E501

        :return: The label of this Footer.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this Footer.

        The footer's text.  # noqa: E501

        :param label: The label of this Footer.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def icon(self):
        """Gets the icon of this Footer.  # noqa: E501

        The footer's icon.  # noqa: E501

        :return: The icon of this Footer.  # noqa: E501
        :rtype: str
        """
        return self._icon

    @icon.setter
    def icon(self, icon):
        """Sets the icon of this Footer.

        The footer's icon.  # noqa: E501

        :param icon: The icon of this Footer.  # noqa: E501
        :type: str
        """

        self._icon = icon

    @property
    def style(self):
        """Gets the style of this Footer.  # noqa: E501


        :return: The style of this Footer.  # noqa: E501
        :rtype: ElementStyle
        """
        return self._style

    @style.setter
    def style(self, style):
        """Sets the style of this Footer.


        :param style: The style of this Footer.  # noqa: E501
        :type: ElementStyle
        """

        self._style = style

    @property
    def url(self):
        """Gets the url of this Footer.  # noqa: E501

        The footer's link, in case the footer links to an external url.  # noqa: E501

        :return: The url of this Footer.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this Footer.

        The footer's link, in case the footer links to an external url.  # noqa: E501

        :param url: The url of this Footer.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def resource_type(self):
        """Gets the resource_type of this Footer.  # noqa: E501

        The type of resource, in case the footer links to a lumapps resource.  # noqa: E501

        :return: The resource_type of this Footer.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this Footer.

        The type of resource, in case the footer links to a lumapps resource.  # noqa: E501

        :param resource_type: The resource_type of this Footer.  # noqa: E501
        :type: str
        """

        self._resource_type = resource_type

    @property
    def resource_id(self):
        """Gets the resource_id of this Footer.  # noqa: E501

        The id of the resource, in case the footer links to a lumapps resource.  # noqa: E501

        :return: The resource_id of this Footer.  # noqa: E501
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id):
        """Sets the resource_id of this Footer.

        The id of the resource, in case the footer links to a lumapps resource.  # noqa: E501

        :param resource_id: The resource_id of this Footer.  # noqa: E501
        :type: str
        """

        self._resource_id = resource_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(Footer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Footer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
