# coding: utf-8

"""
    CMS Contribution API

    The CMS Contribution API allows access and modification of Lumapps contents.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class GetAttendeesResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "attendees": "list[UserReference]",
        "more": "bool",
        "cursor": "str",
    }

    attribute_map = {"attendees": "attendees", "more": "more", "cursor": "cursor"}

    def __init__(self, attendees=None, more=None, cursor=None):  # noqa: E501
        """GetAttendeesResponse - a model defined in Swagger"""  # noqa: E501
        self._attendees = None
        self._more = None
        self._cursor = None
        self.discriminator = None
        if attendees is not None:
            self.attendees = attendees
        if more is not None:
            self.more = more
        if cursor is not None:
            self.cursor = cursor

    @property
    def attendees(self):
        """Gets the attendees of this GetAttendeesResponse.  # noqa: E501

        The attendees of the event sorted by email  # noqa: E501

        :return: The attendees of this GetAttendeesResponse.  # noqa: E501
        :rtype: list[UserReference]
        """
        return self._attendees

    @attendees.setter
    def attendees(self, attendees):
        """Sets the attendees of this GetAttendeesResponse.

        The attendees of the event sorted by email  # noqa: E501

        :param attendees: The attendees of this GetAttendeesResponse.  # noqa: E501
        :type: list[UserReference]
        """

        self._attendees = attendees

    @property
    def more(self):
        """Gets the more of this GetAttendeesResponse.  # noqa: E501

        Whether there is more attendees to load.  # noqa: E501

        :return: The more of this GetAttendeesResponse.  # noqa: E501
        :rtype: bool
        """
        return self._more

    @more.setter
    def more(self, more):
        """Sets the more of this GetAttendeesResponse.

        Whether there is more attendees to load.  # noqa: E501

        :param more: The more of this GetAttendeesResponse.  # noqa: E501
        :type: bool
        """

        self._more = more

    @property
    def cursor(self):
        """Gets the cursor of this GetAttendeesResponse.  # noqa: E501

        The cursor for loading more attendees, if any.  # noqa: E501

        :return: The cursor of this GetAttendeesResponse.  # noqa: E501
        :rtype: str
        """
        return self._cursor

    @cursor.setter
    def cursor(self, cursor):
        """Sets the cursor of this GetAttendeesResponse.

        The cursor for loading more attendees, if any.  # noqa: E501

        :param cursor: The cursor of this GetAttendeesResponse.  # noqa: E501
        :type: str
        """

        self._cursor = cursor

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(GetAttendeesResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetAttendeesResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
