# coding: utf-8

"""
    CMS Contribution API

    The CMS Contribution API allows access and modification of Lumapps contents.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class MultilangObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        "lang": "str",
        "value": "object",
        "translations": "dict(str, object)",
    }

    attribute_map = {"lang": "lang", "value": "value", "translations": "translations"}

    def __init__(self, lang=None, value=None, translations=None):  # noqa: E501
        """MultilangObject - a model defined in Swagger"""  # noqa: E501
        self._lang = None
        self._value = None
        self._translations = None
        self.discriminator = None
        self.lang = lang
        self.value = value
        self.translations = translations

    @property
    def lang(self):
        """Gets the lang of this MultilangObject.  # noqa: E501

        The lang of the translated object  # noqa: E501

        :return: The lang of this MultilangObject.  # noqa: E501
        :rtype: str
        """
        return self._lang

    @lang.setter
    def lang(self, lang):
        """Sets the lang of this MultilangObject.

        The lang of the translated object  # noqa: E501

        :param lang: The lang of this MultilangObject.  # noqa: E501
        :type: str
        """
        if lang is None:
            raise ValueError(
                "Invalid value for `lang`, must not be `None`"
            )  # noqa: E501

        self._lang = lang

    @property
    def value(self):
        """Gets the value of this MultilangObject.  # noqa: E501

        The translated object  # noqa: E501

        :return: The value of this MultilangObject.  # noqa: E501
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this MultilangObject.

        The translated object  # noqa: E501

        :param value: The value of this MultilangObject.  # noqa: E501
        :type: object
        """
        if value is None:
            raise ValueError(
                "Invalid value for `value`, must not be `None`"
            )  # noqa: E501

        self._value = value

    @property
    def translations(self):
        """Gets the translations of this MultilangObject.  # noqa: E501


        :return: The translations of this MultilangObject.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._translations

    @translations.setter
    def translations(self, translations):
        """Sets the translations of this MultilangObject.


        :param translations: The translations of this MultilangObject.  # noqa: E501
        :type: dict(str, object)
        """
        if translations is None:
            raise ValueError(
                "Invalid value for `translations`, must not be `None`"
            )  # noqa: E501

        self._translations = translations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(MultilangObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MultilangObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
