# coding: utf-8

"""
    CMS Contribution API

    The CMS Contribution API allows access and modification of Lumapps contents.   # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class WidgetResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {"widget": "Widget", "more": "bool", "cursor": "str"}

    attribute_map = {"widget": "widget", "more": "more", "cursor": "cursor"}

    def __init__(self, widget=None, more=None, cursor=None):  # noqa: E501
        """WidgetResponse - a model defined in Swagger"""  # noqa: E501
        self._widget = None
        self._more = None
        self._cursor = None
        self.discriminator = None
        self.widget = widget
        self.more = more
        if cursor is not None:
            self.cursor = cursor

    @property
    def widget(self):
        """Gets the widget of this WidgetResponse.  # noqa: E501


        :return: The widget of this WidgetResponse.  # noqa: E501
        :rtype: Widget
        """
        return self._widget

    @widget.setter
    def widget(self, widget):
        """Sets the widget of this WidgetResponse.


        :param widget: The widget of this WidgetResponse.  # noqa: E501
        :type: Widget
        """
        if widget is None:
            raise ValueError(
                "Invalid value for `widget`, must not be `None`"
            )  # noqa: E501

        self._widget = widget

    @property
    def more(self):
        """Gets the more of this WidgetResponse.  # noqa: E501

        Whether more display elements can be loaded for the widget.  # noqa: E501

        :return: The more of this WidgetResponse.  # noqa: E501
        :rtype: bool
        """
        return self._more

    @more.setter
    def more(self, more):
        """Sets the more of this WidgetResponse.

        Whether more display elements can be loaded for the widget.  # noqa: E501

        :param more: The more of this WidgetResponse.  # noqa: E501
        :type: bool
        """
        if more is None:
            raise ValueError(
                "Invalid value for `more`, must not be `None`"
            )  # noqa: E501

        self._more = more

    @property
    def cursor(self):
        """Gets the cursor of this WidgetResponse.  # noqa: E501

        The cursor for loading more display elements, if any.  # noqa: E501

        :return: The cursor of this WidgetResponse.  # noqa: E501
        :rtype: str
        """
        return self._cursor

    @cursor.setter
    def cursor(self, cursor):
        """Sets the cursor of this WidgetResponse.

        The cursor for loading more display elements, if any.  # noqa: E501

        :param cursor: The cursor of this WidgetResponse.  # noqa: E501
        :type: str
        """

        self._cursor = cursor

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value
        if issubclass(WidgetResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WidgetResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
