---
name: 'Check commit message'

on: [pull_request]  # yamllint disable-line rule:truthy

jobs:
  commit-message-validation:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Commit message validation
        uses: lumapps/commit-message-validator@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_VALIDATOR_NO_JIRA: true
          COMMIT_VALIDATOR_ALLOW_TEMP: true